pipeline {
    agent any
    stages {
        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    script {
                        sh "terraform init"
                        sh "opa"
                    }
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    script {
                        sh "terraform plan --out plan.tfplan"
                        sh "terraform show plan.tfplan > plan.json"
                    }
                }
            }
        }
        stage('OPA Policy Enforcement') {
            steps {
                dir('rego') {
                    script {
                        sh 'opa eval --data tags_keys.rego --input ../Terraform/plan.json "data.main.allow"'
                    }
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('Terraform') {
                    script {
                        sh ""
                    }
                }
            }
        }
    }
}