pipeline {
    agent any
    stages {
        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    script {
                        sh "terraform init"
                        sh "opa"
                    }
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    script {
                        sh "terraform plan --out tfplan.binary"
                        sh "terraform show -json tfplan.binary > tfplan.json"
                    }
                }
            }
        }
        stage('OPA Policy Enforcement') {
            steps {
                dir('rego') {
                    script {
                        sh 'opa eval --data tags_keys.rego --input ../Terraform/tfplan.json "terraform.aws_instance_tag_policy.deny"'
                    }
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('Terraform') {
                    script {
                        sh ""
                    }
                }
            }
        }
        post {
            failure {
                dir('Terraform') {
                    script {
                        sh "rm -rf tfplan.binary tfplan.json"
                    }
                }
            }
        }
    }
}