pipeline {
    agent any
    stages {
        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    script {
                        sh "terraform init"
                        sh "opa"
                    }
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    script {
                        sh "terraform plan -out=tfplan"
                    }
                }
            }
        }
        stage('OPA Policy Enforcement') {
            steps {
                dir('Terraform') {
                    script {
                        sh 'opa eval --data policy.rego --input tfplan "data.main.allow"'
                    }
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('Terraform') {
                    script {
                        sh "pwd"
                    }
                }
            }
        }
    }
}